<?php
$priceModel = $block->getPriceType('regular_price');
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if ($block->hasSpecialPrice()): ?>
	<span class="special-price">
        <?php  echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label' 	=> __('Special Price'),
            'price_id'      	=> $block->getPriceId('product-price-' . $idSuffix),
    	    'price_type'    	=> 'finalPrice',
            'include_container' => true,
            'schema' => $schema
    	]); ?>
    </span>
	<span class="percentage-discount">
	<?php
	$item = $block->getSaleableItem();

    // $item->getFinalPrice()

    $_savePercent = 100 - round(((float)$item->getPriceInfo()->getPrice('final_price')->getAmount()->getValue() / (float)$item->getPrice()) * 100);
	echo '(<b>'.$_savePercent . '% off </b>)';

	?>
    </span>
    <br>
	<span class="old-price">
        <?php  echo $block->renderAmount($priceModel->getAmount(), [
        	'display_label' 	=> __('Regular Price'),
            'price_id'      	=> $block->getPriceId('old-price-' . $idSuffix),
            'price_type'    	=> 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
	    ]); ?>
    </span> 
    Save <?php echo '&#8358;' . number_format((float)$item->getPrice() - (float)$item->getPriceInfo()->getPrice('final_price')->getAmount()->getValue())   ?>
<?php else: ?>
    <?php  echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'      	=> $block->getPriceId('product-price-' . $idSuffix),
        'price_type'    	=> 'finalPrice',
        'include_container' => true,
    	'schema' => $schema
	]); ?>
<?php endif; ?>
 
<?php if ($block->showMinimalPrice()): ?>
	<?php if ($block->getUseLinkForAsLowAs()):?>
    	<a href="<?=  $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= $block->renderAmountMinimal() ?>
        </a>
	<?php else:?>
    	<span class="minimal-price-link">
            <?=  $block->renderAmountMinimal() ?>
        </span>
	<?php endif?>
<?php endif; ?>
<p>
    Same Day Delivery
	<!-- Delivery Time: 3 - 24hrs -->
</p>